### ISSUE TITLE
Not working with pynwb v1.2.1

### ISSUE THREAD

**Issue by filippomc** [NeurodataWithoutBorders/nwb-jupyter-widgets#96]
Hi,
when importing nwbwidgets with pynwb v1.2.1 installed the following error occurs:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/nwb/lib/python3.7/site-packages/nwbwidgets/__init__.py", line 1, in <module>
    from .view import nwb2widget
  File "/opt/conda/envs/nwb/lib/python3.7/site-packages/nwbwidgets/view.py", line 6, in <module>
    from nwbwidgets import behavior, misc, base, ecephys, image, ophys
  File "/opt/conda/envs/nwb/lib/python3.7/site-packages/nwbwidgets/base.py", line 8, in <module>
    from pynwb.core import DynamicTable, NWBBaseType
ImportError: cannot import name 'NWBBaseType' from 'pynwb.core' (/opt/conda/envs/nwb/lib/python3.7/site-packages/pynwb/core.py)
```

**Comment by pgleeson** [comment]
@filippomc Is this relevant any more if NWBE is using pynwb 1.3.0?

**Comment by filippomc** [comment]
@pgleeson this was fixed with the new nwbwidgets. Closing.
